#welcome screen - general

'''MASTERMIND AND COWS AND BULLS
COMPUTER SCIENCE ICUP MINI PROJECT 2018-19

AUTHORS (all from Section G):

ADITHI SATISH PES1201800150
DRISHTI HOSKOTE PES1201801283
KHUSHEI MEDA PES1201800416

The project that we've chosen to do are mastermind and cows and bulls. Since Mastermind and Cows and Bulls work on the same logic, C&B being comparitively harder, it can funtion as two levels of a single game.
This project is dependant on the graphics.py library which was downloaded from the internet.
The major concepts used in this project are:
Creation and Linking of Multiple Modules
Parameterised functions and functions without parameters
Functional Programming (i.e lambda)
Immutable property of tuples and strings
List Slicing
Built in functions
File Handling: Reading and Appending into a file

Extra concepts learnt:
The basics of classes (since we finished most of the game before OOP concepts was taught in class, we learnt only the basics of classes in order to understand the functionality of the graphics library
Functions in graphics.py

Application:
Since the project is a game, it mainly is used for leisure. The game also tests the user's logical aptitude.'''

from mastermind_game_screen import *
from cowsandbulls_main import *
from highscore import *

score = []

#to accept the name of the player:
win1 = GraphWin("Name",400,400)
win1.setBackground("black")
t = Text(Point(200,150),'Enter your name: ')
t.setTextColor('white')
t.draw(win1)
name = Entry(Point(200,200),20)
name.draw(win1)
win1.getMouse()
score.append(name.getText())
timelag()
win1.close()
#print(score)

#to create window for menu:
win = GraphWin("Welcome",800,600)
win.setBackground('black')

def printtext(dwin,x,y,text,size = 15,color = 'white',style = 'normal'): #this is a function that has all functions of Text class so that printing text is easy
    txt = Text(Point(x,y),text)
    txt.setSize(size)
    txt.setTextColor(color)
    txt.setStyle(style)
    txt.draw(dwin)

def instructions(): #prints instructions

    in_win = GraphWin("Instructions Window",800,600)
    s = "INSTRUCTIONS"
    m1 = 'FOR MASTERMIND:\n A FOUR COLOR UNIQUE CODE IS RANDOMLY GENERATED BY THE COMPUTER. \nYOUR OBJECTIVE IS TO GUESS THE CODE. \nYOU CAN CLICK ON FOUR CIRCLES IN EACH CHANCE.\nYOUR OPTION IS COMPARED WITH THE GENERATED CODE AND IT RETURNS THE FOLLOWING:'
    m2 = 'THE COLOR IS PRESENT IN THE SAME POSITION: GREEN RECTANGLE\nTHE COLOR IS PRESENT BUT IN A DIFFERENT POSITION:YELLOW RECTANGLE\nIF THE COLOR IS NOT PRESENT IN THE CODE: RED RECTANGLE'
    s1 = 'YOU HAVE TEN TURNS TO GUESS THE CORRECT CODE IN BOTH GAMES'

    c1 = 'FOR COWS AND BULLS:\n A RANDOM FOUR DIGIT NUMBER IS GENERATED BY THE COMPUTER, WHICH YOU HAVE TO GUESS. \nEACH TURN YOU ENTER A NUMBER WHICH IS THEN COMPARED TO THE GENERATED ONE.'
    c2 = 'THE DIGIT IS PRESENT IN THE SAME POSITION: 1 COW\nTHE DIGIT IS PRESENT BUT IN A DIFFERENT POSITION: 1 BULL'

    printtext(in_win,400,50,s,18,'green','bold')
    x = 400;sz = 12
    printtext(in_win,x,150,m1,sz,'red')
    printtext(in_win,x,230,m2,sz,'red')
    printtext(in_win,x,370,c1,sz,'purple')
    printtext(in_win,x,420,c2,sz,'purple')
    printtext(in_win,x,550,s1,15,'green','bold')

    in_win.getMouse()
    timelag()
    in_win.close()
    
    
def head(): #to print the heading in the window
    
    t = 'WELCOME TO THE GAMING ZONE. \n\nTHE GAMES OFFERED ARE MASTERMIND AND COWS AND BULLS'
    printtext(win,400,100,t,18,'light green','bold italic')

def main(): #the backbone of the program, calls respective functions based on choice entered by the user

    head()
    
    t = ['MASTERMIND','COWS AND BULLS','INSTRUCTIONS (for both)','HIGH SCORES','QUIT']
    t1 = Text(Point(100,200),"CLICK ON ANY OF THE BUTTONS BELOW TO CHOOSE YOUR OPTION")
    x = 150;y = 250

    for i in t: #prints cricles for the user to choose from
        c = Circle(Point(x,y),20)
        c.setFill('red')
        c.draw(win)
        printtext(win,x+180,y,i,18,'yellow')
        y+=70

    while True:
        
        pt = win.getMouse()
        if pt.x >=130 and pt.x<=170:
            
            if pt.y >=230 and pt.y<=270:
                win.close()
                score.append('M')
                score.insert(1,mastermind_main()) #mastermind_main is returning score which is then inserted as the first element in the score list
                #print(score)
                highscore(str(score)+'\n')
            elif pt.y >=300 and pt.y<=340:
                win.close()
                score.append("C&B")
                score.insert(1,cows_and_bulls()) #cows and bulls also returns score
                #print(score)
                highscore(str(score)+'\n')
            elif pt.y>=370 and pt.y<=410:
                #win.close()
                instructions() #displays instructions
                #main()
            elif pt.y>=440 and pt.y<=480:
                win.close()
                print_hs(score) #opens file HighScores.txt, sorts and prints scores
            elif pt.y>=510 and pt.y<=550:
                win.close()
                break
        #main()
            

#head()
main()
